// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// objfcpp
NumericVector objfcpp(NumericVector eps2, NumericVector sigma2, SEXP omega_, SEXP alpha_, SEXP beta_, SEXP r_, SEXP n_, SEXP tol_);
RcppExport SEXP EbEEMGARCH_objfcpp(SEXP eps2SEXP, SEXP sigma2SEXP, SEXP omega_SEXP, SEXP alpha_SEXP, SEXP beta_SEXP, SEXP r_SEXP, SEXP n_SEXP, SEXP tol_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type eps2(eps2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type omega_(omega_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type alpha_(alpha_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type beta_(beta_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type r_(r_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_(n_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type tol_(tol_SEXP);
    __result = Rcpp::wrap(objfcpp(eps2, sigma2, omega_, alpha_, beta_, r_, n_, tol_));
    return __result;
END_RCPP
}
// objfcpp2
NumericVector objfcpp2(NumericVector eps2, NumericVector sigma2, SEXP omega_, SEXP alpha_, SEXP beta_, SEXP n_);
RcppExport SEXP EbEEMGARCH_objfcpp2(SEXP eps2SEXP, SEXP sigma2SEXP, SEXP omega_SEXP, SEXP alpha_SEXP, SEXP beta_SEXP, SEXP n_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type eps2(eps2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type omega_(omega_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type alpha_(alpha_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type beta_(beta_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_(n_SEXP);
    __result = Rcpp::wrap(objfcpp2(eps2, sigma2, omega_, alpha_, beta_, n_));
    return __result;
END_RCPP
}
