# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

objfcpp <- function(eps2, sigma2, omega_, alpha_, beta_, r_, n_, tol_) {
    .Call('EbEEMGARCH_objfcpp', PACKAGE = 'EbEEMGARCH', eps2, sigma2, omega_, alpha_, beta_, r_, n_, tol_)
}

objfcpp2 <- function(eps2, sigma2, omega_, alpha_, beta_, n_) {
    .Call('EbEEMGARCH_objfcpp2', PACKAGE = 'EbEEMGARCH', eps2, sigma2, omega_, alpha_, beta_, n_)
}

